
UpdateChecker:
  enabled: true
  auto_update: true

Options:
  Lobby:
    auto_teleport_on_join: false
  OnJoin:
    custom_join_messages: true
  Vanish:
    enabled: true

Lang:
  discord: 'Put your discord link here!'
  not_enough_args: '&4You have not provided the correct amount of arguments!'
  no_permission: '&4You do not have permission to execute this command!'
  sender_not_player: '&4Only players can execute this command!'
  prefix: '&2[&6SH+&2]&7&r ' #Remember to add a space after if you ever modify the prefix! To remove the prefix simply set it to ''
  invalid_player: '&4That player is either offline or does not exist!'
  string_not_int: '&4You must enter a integer not a string!'
  custom_join_message: '&6Welcome to the server %p!' # %p is replaced with the players display name
  vanished: '&6You are now &avanished'
  unvanished: '&6You are now &cunvanished'

Locations: {}