
Lang:
  discord: 'Put your discord link here!'
  no-permission: '&4You do not have permission to execute this command!'
  sender_not_player: '&4Only players can execute this command!'
  prefix: '&2[&6SH+&2]&7'