name: ServerHubsPlus
version: 1.6
main: me.xaxis.serverhubsplus.ServerHubsPlus
api-version: 1.19
authors:
  - Xaxis
description: This is packed with all the essentials you need for your plugin!
commands:
  heal:
    description: 'Heal yourself'
  sethub:
    description: 'set hub'
    aliases:
      - setlobby
  hub:
    aliases:
      - lobby
    description: 'Teleport to hub'
  tphere:
    description: 'Teleport a player to your location'
  tp2p:
    description: 'tp to a player'
  suicide:
    description: 'kill yourself'
  fly:
    description: 'enable/disable flying'
  godmode:
    description: 'make yourself invulnerable'
  vanish:
    description: 'make yourself invisible to certain players'
  discord:
    description: 'Your discord link'
  invsee:
    description: 'Look into another players inventory and remove items'

