name: ServerHubsPlus
version: ${project.version}
main: me.xaxis_playz.shp.serverhubsplus.ServerHubsPlus
api-version: 1.14
authors: [Xaxis_Playz]
description: This is packed with all the essentials you need for your plugin!
website: https://www.youtube.com/channel/UCqsW72sUu2UgLnURN_NAl-A?view_as=subscriber
commands:
  heal:
    description: 'Heal yourself'
  sethub:
    description: 'set hub'
    aliases:
      - setlobby
  hub:
    aliases:
      - lobby
    description: 'Teleport to hub'
  vanish:
    aliases:
      - v
    description: 'Vanish yourself or others'
